# NumPy

Podstawowa biblioteka naukowo-obliczeniowa. Główny obiekt to `ndarray` - "n-dimensional array".

#### Zadanie 1

Stwórz dwuwymiarową tablicę 4x3 `a` wypełnioną zerami.

Stwórz dwuwymiarową tablicę 4x3 `b` wypełnioną liczbami od 11 do 22.

Jakie są typy danych w obu tych tablicach?

W tablicy `a`:

- przypisz wartości pierwszej kolumny tablicy `b` do komórek pierwszej kolumny
- przypisz wartość 0.5 do ostatnich dwóch komórek środkowej kolumny
- przypisz wartość 1 do komórek ostatniej kolumny

Oczekiwany końcowy wygląd tablicy `a`:

```
[[ 11 0   1 ]
 [ 14 0   1 ]
 [ 17 0.5 1 ]
 [ 20 0.5 1 ]]
```

In [1]:
import numpy as np

In [2]:
a = np.zeros(12).reshape(4, 3)
b = np.arange(11, 23).reshape(4, 3)
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [3]:
a.dtype, b.dtype

(dtype('float64'), dtype('int64'))

In [4]:
a[:, 0] = b[:, 0]
a[2:, 1] = 0.5
a[:, 2] = 1
print(a)

[[11.   0.   1. ]
 [14.   0.   1. ]
 [17.   0.5  1. ]
 [20.   0.5  1. ]]


## Operacje na tablicach - NumPy Universal Functions

Porównanie czasu obliczenia liczb odwrotnych do podanych na dużej ilości elementów.

In [5]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = []
    for i in range(len(values)):
        output.append(1.0 / values[i])
    return output

values = np.random.randint(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

[6 1 4 4 8]
[0.16666666666666666, 1.0, 0.25, 0.25, 0.125]


In [6]:
big_array = np.random.randint(1, 100, size=1000000)
print(big_array[0:10])

[10 84 22 37 88 71 89 89 13 59]


In [7]:
print(compute_reciprocals(big_array)[0:10])
%timeit compute_reciprocals(big_array)

[0.1, 0.011904761904761904, 0.045454545454545456, 0.02702702702702703, 0.011363636363636364, 0.014084507042253521, 0.011235955056179775, 0.011235955056179775, 0.07692307692307693, 0.01694915254237288]
1.57 s ± 44.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
print((1.0 / big_array)[0:10])
%timeit (1.0 / big_array)

[0.1        0.01190476 0.04545455 0.02702703 0.01136364 0.01408451
 0.01123596 0.01123596 0.07692308 0.01694915]
1.06 ms ± 59 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### Zadanie 2

Tablica `t` zawiera kolejne rekordy opisujące trójkąty prostokątne, gdzie kolejne kolumny to:

0. długość boku a
1. długość boku b
2. długość boku c - przeciwprostokątnej
3. suma długości boków

```
  |\
  | \
a |  \ c
  |   \
  |____\
     b
```

- uzupełnij kolumny 2 i 3
- podaj sumaryczną długość boków wszystkich trójkątów

Długość boku c można obliczyć z Twierdzenia Pitagorasa:

$$a^2+b^2=c^2$$

Do obliczenia pierwiastka kwadratowego służy funkcja `np.sqrt()`.

In [9]:
t = np.array([
    [3, 4, 0, 0],
    [5, 12, 0, 0],
    [8, 15, 0, 0],
    [7, 24, 0, 0],
    [9, 40, 0, 0],
])
t

array([[ 3,  4,  0,  0],
       [ 5, 12,  0,  0],
       [ 8, 15,  0,  0],
       [ 7, 24,  0,  0],
       [ 9, 40,  0,  0]])

In [10]:
t[:,2] = np.sqrt((t[:,0] ** 2) + (t[:,1] ** 2))
t

array([[ 3,  4,  5,  0],
       [ 5, 12, 13,  0],
       [ 8, 15, 17,  0],
       [ 7, 24, 25,  0],
       [ 9, 40, 41,  0]])

In [11]:
t[:,3] = np.sum(t[:,0:3], axis=1)
t

array([[ 3,  4,  5, 12],
       [ 5, 12, 13, 30],
       [ 8, 15, 17, 40],
       [ 7, 24, 25, 56],
       [ 9, 40, 41, 90]])

In [12]:
np.sum(t[:, 3])

228